// Generated by scripts/igp24_offline_verify.py
// Manual MAGMA input for proxy-only IGP24 review candidates.
// Exact GaloisGroup calls are left commented for deliberate local use.

Zx<x> := PolynomialRing(Integers());
candidates := [
  <"425c30453d4a687477904ed655aa27673e6d51558794aeacf7efe43bb94b4204", [1, 0, 0, 0, 0, 0, -8, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 1]>,
];

for rec in candidates do
  h := rec[1];
  coeffs := rec[2];
  f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
  print "BEGIN", h;
  print f;
  print "IsIrreducible", IsIrreducible(f);
  print "NumberOfRealRoots", NumberOfRealRoots(f);
  // Optional exact step, intentionally manual:
  // G, roots, data := GaloisGroup(f);
  // print "GaloisGroup", G;
  // print "TransitiveGroupIdentification", TransitiveGroupIdentification(G);
  print "END", h;
end for;
