// Generated by scripts/igp24_offline_verify.py
// Manual MAGMA input for proxy-only IGP24 review candidates.
// Exact GaloisGroup calls are left commented for deliberate local use.

Zx<x> := PolynomialRing(Integers());
candidates := [
  <"8f32835b516ddb4ad27c12ed38e67025d0f13cdb790e28a38473c49bd3c9e1f7", [371, 0, -10584, 0, 60228, 0, -178248, 0, 307804, 0, -327726, 0, 221271, 0, -96216, 0, 27175, 0, -4950, 0, 561, 0, -36, 0, 1]>,
];

for rec in candidates do
  h := rec[1];
  coeffs := rec[2];
  f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
  print "BEGIN", h;
  print f;
  print "IsIrreducible", IsIrreducible(f);
  print "NumberOfRealRoots", NumberOfRealRoots(f);
  // Optional exact step, intentionally manual:
  // G, roots, data := GaloisGroup(f);
  // print "GaloisGroup", G;
  // print "TransitiveGroupIdentification", TransitiveGroupIdentification(G);
  print "END", h;
end for;
