// Generated by scripts/igp24_offline_verify.py
// Manual MAGMA input for proxy-only IGP24 review candidates.
// Exact GaloisGroup calls are left commented for deliberate local use.

Zx<x> := PolynomialRing(Integers());
candidates := [
  <"4b6fc17867226448a51aced431465fb37f29400ca35f3234aff13ab0ea4c6bb7", [108, 0, 0, 0, 0, 0, -176, 0, 0, 0, 0, 0, 86, 0, 0, 0, 0, 0, -16, 0, 0, 0, 0, 0, 1]>,
  <"d4aed028ad972072f94586e017a8349bd142ea10f30e5e2062db78406c35b4fd", [39, 0, 0, 0, 0, 0, -78, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 1]>,
  <"caa861f3b409b480c883e1d4bb6ef797eca09f5d68dbff0472d86a7624071971", [38, 0, 0, 0, 0, 0, -78, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 1]>,
  <"5f06b5464de967f57a92a0085561a48741483fb8c03c053965be0c497e7cecaf", [37, 0, 0, 0, 0, 0, -78, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 1]>,
];

for rec in candidates do
  h := rec[1];
  coeffs := rec[2];
  f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
  print "BEGIN", h;
  print f;
  print "IsIrreducible", IsIrreducible(f);
  print "NumberOfRealRoots", NumberOfRealRoots(f);
  // Optional exact step, intentionally manual:
  // G, roots, data := GaloisGroup(f);
  // print "GaloisGroup", G;
  // print "TransitiveGroupIdentification", TransitiveGroupIdentification(G);
  print "END", h;
end for;
