\\ Generated by scripts/igp24_offline_verify.py
\\ Manual PARI/GP input for IGP24 review candidates.
\\ This script prints official-style exact nfdisc evidence.
\\ It does not submit to SAIR and should stay outside training/search loops.

x = 'x;
pol_from_coeffs(v) = sum(i = 1, #v, v[i] * x^(i - 1));

candidates = [\
  ["ee63944ba7bf61dde03b31907636e85b3cea05f648ae1f0a2918d629fd29c825", [5039, 0, -48168, 0, 191772, 0, -420888, 0, 567244, 0, -494802, 0, 287001, 0, -112056, 0, 29455, 0, -5130, 0, 567, 0, -36, 0, 1]]\
];

for (i = 1, #candidates,\
  h = candidates[i][1];\
  coeffs = candidates[i][2];\
  f = pol_from_coeffs(coeffs);\
  print("IGP24_PARI_BEGIN ", h);\
  print("IGP24_PARI_DEGREE ", poldegree(f));\
  print("IGP24_PARI_IS_IRREDUCIBLE ", polisirreducible(f));\
  print("IGP24_PARI_REAL_ROOT_COUNT ", polsturm(f));\
  print("IGP24_POLDISC_ABS ", abs(poldisc(f)));\
  iferr(\
    nfd = abs(nfdisc(f));\
    print("IGP24_NFDISC_ABS ", nfd);\
    print("IGP24_NFDISC_STATUS ok"),\
    E,\
    print("IGP24_NFDISC_STATUS error");\
    print("IGP24_NFDISC_ERROR ", E)\
  );\
  print("IGP24_PARI_END ", h);\
);
