// Generated by scripts/igp24_offline_verify.py
// MAGMA per-candidate exact verifier script schema 1.
// External timeout managed by Python helper: 90 seconds.
SetSeed(1);
Zx<x> := PolynomialRing(Integers());
candidate_hash := "9a6203690a2842ad02462d00b009912ef02606c2c5df914710a96e03825258e2";
coeffs := [719, 0, -10584, 0, 60228, 0, -178248, 0, 307804, 0, -327726, 0, 221271, 0, -96216, 0, 27175, 0, -4950, 0, 561, 0, -36, 0, 1];
f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
print "IGP24_BEGIN", candidate_hash;
print "IGP24_DEGREE", Degree(f);
print "IGP24_IS_IRREDUCIBLE", IsIrreducible(f);
r := NumberOfRealRoots(f);
print "IGP24_SIGNATURE", r;
G, roots, data := GaloisGroup(f);
print "IGP24_GALOIS_GROUP", G;
tid := TransitiveGroupIdentification(G);
print "IGP24_TRANSITIVE_GROUP_ID", tid;
print "IGP24_END", candidate_hash;
quit;
