// Generated by scripts/igp24_offline_verify.py
// MAGMA per-candidate exact verifier script schema 1.
// External timeout managed by Python helper: 240 seconds.
SetSeed(1);
Zx<x> := PolynomialRing(Integers());
candidate_hash := "425c30453d4a687477904ed655aa27673e6d51558794aeacf7efe43bb94b4204";
coeffs := [1, 0, 0, 0, 0, 0, -8, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, -9, 0, 0, 0, 0, 0, 1];
f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
print "IGP24_BEGIN", candidate_hash;
print "IGP24_DEGREE", Degree(f);
print "IGP24_IS_IRREDUCIBLE", IsIrreducible(f);
r := NumberOfRealRoots(f);
print "IGP24_SIGNATURE", r;
G, roots, data := GaloisGroup(f);
print "IGP24_GALOIS_GROUP", G;
tid := TransitiveGroupIdentification(G);
print "IGP24_TRANSITIVE_GROUP_ID", tid;
print "IGP24_END", candidate_hash;
quit;
