// Generated by scripts/igp24_offline_verify.py
// Online MAGMA manual copy/paste script schema 1.
// Paste manually at https://magma.maths.usyd.edu.au/calc/; do not batch-submit.
// Observed calculator caps: 60s, 50000 bytes, Magma V2.29-8.
SetSeed(1);
Zx<x> := PolynomialRing(Integers());
candidate_hash := "4b6fc17867226448a51aced431465fb37f29400ca35f3234aff13ab0ea4c6bb7";
coeffs := [108, 0, 0, 0, 0, 0, -176, 0, 0, 0, 0, 0, 86, 0, 0, 0, 0, 0, -16, 0, 0, 0, 0, 0, 1];
f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
print "IGP24_BEGIN", candidate_hash;
print "IGP24_DEGREE", Degree(f);
print "IGP24_IS_IRREDUCIBLE", IsIrreducible(f);
r := NumberOfRealRoots(f);
print "IGP24_SIGNATURE", r;
G, roots, data := GaloisGroup(f);
print "IGP24_GALOIS_GROUP", G;
tid := TransitiveGroupIdentification(G);
print "IGP24_TRANSITIVE_GROUP_ID", tid;
print "IGP24_END", candidate_hash;
quit;
