// Generated by scripts/igp24_offline_verify.py
// Manual MAGMA input for proxy-only IGP24 review candidates.
// Exact GaloisGroup calls are left commented for deliberate local use.

Zx<x> := PolynomialRing(Integers());
candidates := [
  <"9da7a6f4dac4a3f9aec5b7a8a5fd7439c2ea3508da77689cc16cab0c7de6ca0e", [5042, 0, -48168, 0, 191772, 0, -420888, 0, 567244, 0, -494802, 0, 287001, 0, -112056, 0, 29455, 0, -5130, 0, 567, 0, -36, 0, 1]>,
  <"16a66dd8583f7f612e350a3c5f921a7d74317946c077f21f27e7858a677f3e98", [722, 0, -10584, 0, 60228, 0, -178248, 0, 307804, 0, -327726, 0, 221271, 0, -96216, 0, 27175, 0, -4950, 0, 561, 0, -36, 0, 1]>,
  <"093d4ca1da4c1f437c3313e3bf40eb0a5d0a1b0ed5805b3eca639ff6ed668220", [20163, 0, -147312, 0, 462096, 0, -823008, 0, 927454, 0, -697518, 0, 359751, 0, -128616, 0, 31765, 0, -5310, 0, 573, 0, -36, 0, 1]>,
  <"b03eb2c2a86a9e2bef2de3683672347889e43bf31ee07cb8a8b45df74b8e05ce", [20159, 0, -147312, 0, 462096, 0, -823008, 0, 927454, 0, -697518, 0, 359751, 0, -128616, 0, 31765, 0, -5310, 0, 573, 0, -36, 0, 1]>,
];

for rec in candidates do
  h := rec[1];
  coeffs := rec[2];
  f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
  print "BEGIN", h;
  print f;
  print "IsIrreducible", IsIrreducible(f);
  print "NumberOfRealRoots", NumberOfRealRoots(f);
  // Optional exact step, intentionally manual:
  // G, roots, data := GaloisGroup(f);
  // print "GaloisGroup", G;
  // print "TransitiveGroupIdentification", TransitiveGroupIdentification(G);
  print "END", h;
end for;
