// Generated by scripts/igp24_offline_verify.py
// Online MAGMA manual copy/paste script schema 1.
// Paste manually at https://magma.maths.usyd.edu.au/calc/; do not batch-submit.
// Observed calculator caps: 60s, 50000 bytes, Magma V2.29-8.
SetSeed(1);
Zx<x> := PolynomialRing(Integers());
candidate_hash := "16a66dd8583f7f612e350a3c5f921a7d74317946c077f21f27e7858a677f3e98";
coeffs := [722, 0, -10584, 0, 60228, 0, -178248, 0, 307804, 0, -327726, 0, 221271, 0, -96216, 0, 27175, 0, -4950, 0, 561, 0, -36, 0, 1];
f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
print "IGP24_BEGIN", candidate_hash;
print "IGP24_DEGREE", Degree(f);
print "IGP24_IS_IRREDUCIBLE", IsIrreducible(f);
r := NumberOfRealRoots(f);
print "IGP24_SIGNATURE", r;
G, roots, data := GaloisGroup(f);
print "IGP24_GALOIS_GROUP", G;
tid := TransitiveGroupIdentification(G);
print "IGP24_TRANSITIVE_GROUP_ID", tid;
print "IGP24_END", candidate_hash;
quit;
