// Generated by scripts/igp24_offline_verify.py
// Manual MAGMA input for proxy-only IGP24 review candidates.
// Exact GaloisGroup calls are left commented for deliberate local use.

Zx<x> := PolynomialRing(Integers());
candidates := [
  <"ee63944ba7bf61dde03b31907636e85b3cea05f648ae1f0a2918d629fd29c825", [5039, 0, -48168, 0, 191772, 0, -420888, 0, 567244, 0, -494802, 0, 287001, 0, -112056, 0, 29455, 0, -5130, 0, 567, 0, -36, 0, 1]>,
];

for rec in candidates do
  h := rec[1];
  coeffs := rec[2];
  f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
  print "BEGIN", h;
  print f;
  print "IsIrreducible", IsIrreducible(f);
  print "NumberOfRealRoots", NumberOfRealRoots(f);
  // Optional exact step, intentionally manual:
  // G, roots, data := GaloisGroup(f);
  // print "GaloisGroup", G;
  // print "TransitiveGroupIdentification", TransitiveGroupIdentification(G);
  print "END", h;
end for;
