// Generated by scripts/igp24_offline_verify.py
// Online MAGMA manual copy/paste script schema 1.
// Paste manually at https://magma.maths.usyd.edu.au/calc/; do not batch-submit.
// Observed calculator caps: 60s, 50000 bytes, Magma V2.29-8.
SetSeed(1);
Zx<x> := PolynomialRing(Integers());
candidate_hash := "ee63944ba7bf61dde03b31907636e85b3cea05f648ae1f0a2918d629fd29c825";
coeffs := [5039, 0, -48168, 0, 191772, 0, -420888, 0, 567244, 0, -494802, 0, 287001, 0, -112056, 0, 29455, 0, -5130, 0, 567, 0, -36, 0, 1];
f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
print "IGP24_BEGIN", candidate_hash;
print "IGP24_DEGREE", Degree(f);
print "IGP24_IS_IRREDUCIBLE", IsIrreducible(f);
r := NumberOfRealRoots(f);
print "IGP24_SIGNATURE", r;
G, roots, data := GaloisGroup(f);
print "IGP24_GALOIS_GROUP", G;
tid := TransitiveGroupIdentification(G);
print "IGP24_TRANSITIVE_GROUP_ID", tid;
print "IGP24_END", candidate_hash;
quit;
