// Generated by scripts/igp24_offline_verify.py
// MAGMA per-candidate exact verifier script schema 1.
// External timeout managed by Python helper: 90 seconds.
SetSeed(1);
Zx<x> := PolynomialRing(Integers());
candidate_hash := "9da7a6f4dac4a3f9aec5b7a8a5fd7439c2ea3508da77689cc16cab0c7de6ca0e";
coeffs := [5042, 0, -48168, 0, 191772, 0, -420888, 0, 567244, 0, -494802, 0, 287001, 0, -112056, 0, 29455, 0, -5130, 0, 567, 0, -36, 0, 1];
f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
print "IGP24_BEGIN", candidate_hash;
print "IGP24_DEGREE", Degree(f);
print "IGP24_IS_IRREDUCIBLE", IsIrreducible(f);
r := NumberOfRealRoots(f);
print "IGP24_SIGNATURE", r;
G, roots, data := GaloisGroup(f);
print "IGP24_GALOIS_GROUP", G;
tid := TransitiveGroupIdentification(G);
print "IGP24_TRANSITIVE_GROUP_ID", tid;
print "IGP24_END", candidate_hash;
quit;
