// Generated by scripts/igp24_offline_verify.py
// MAGMA per-candidate exact verifier script schema 1.
// External timeout managed by Python helper: 60 seconds.
SetSeed(1);
Zx<x> := PolynomialRing(Integers());
candidate_hash := "5f06b5464de967f57a92a0085561a48741483fb8c03c053965be0c497e7cecaf";
coeffs := [37, 0, 0, 0, 0, 0, -78, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 1];
f := &+[ Integers()!coeffs[i + 1] * x^i : i in [0..#coeffs - 1] ];
print "IGP24_BEGIN", candidate_hash;
print "IGP24_DEGREE", Degree(f);
print "IGP24_IS_IRREDUCIBLE", IsIrreducible(f);
r := NumberOfRealRoots(f);
print "IGP24_SIGNATURE", r;
G, roots, data := GaloisGroup(f);
print "IGP24_GALOIS_GROUP", G;
tid := TransitiveGroupIdentification(G);
print "IGP24_TRANSITIVE_GROUP_ID", tid;
print "IGP24_END", candidate_hash;
quit;
