\\ Generated by scripts/igp24_offline_verify.py
\\ Manual PARI/GP input for IGP24 review candidates.
\\ This script prints official-style exact nfdisc evidence.
\\ It does not submit to SAIR and should stay outside training/search loops.

x = 'x;
pol_from_coeffs(v) = sum(i = 1, #v, v[i] * x^(i - 1));

candidates = [\
  ["4b6fc17867226448a51aced431465fb37f29400ca35f3234aff13ab0ea4c6bb7", [108, 0, 0, 0, 0, 0, -176, 0, 0, 0, 0, 0, 86, 0, 0, 0, 0, 0, -16, 0, 0, 0, 0, 0, 1]],\
  ["d4aed028ad972072f94586e017a8349bd142ea10f30e5e2062db78406c35b4fd", [39, 0, 0, 0, 0, 0, -78, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 1]],\
  ["caa861f3b409b480c883e1d4bb6ef797eca09f5d68dbff0472d86a7624071971", [38, 0, 0, 0, 0, 0, -78, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 1]],\
  ["5f06b5464de967f57a92a0085561a48741483fb8c03c053965be0c497e7cecaf", [37, 0, 0, 0, 0, 0, -78, 0, 0, 0, 0, 0, 49, 0, 0, 0, 0, 0, -12, 0, 0, 0, 0, 0, 1]]\
];

for (i = 1, #candidates,\
  h = candidates[i][1];\
  coeffs = candidates[i][2];\
  f = pol_from_coeffs(coeffs);\
  print("IGP24_PARI_BEGIN ", h);\
  print("IGP24_PARI_DEGREE ", poldegree(f));\
  print("IGP24_PARI_IS_IRREDUCIBLE ", polisirreducible(f));\
  print("IGP24_PARI_REAL_ROOT_COUNT ", polsturm(f));\
  print("IGP24_POLDISC_ABS ", abs(poldisc(f)));\
  iferr(\
    nfd = abs(nfdisc(f));\
    print("IGP24_NFDISC_ABS ", nfd);\
    print("IGP24_NFDISC_STATUS ok"),\
    E,\
    print("IGP24_NFDISC_STATUS error");\
    print("IGP24_NFDISC_ERROR ", E)\
  );\
  print("IGP24_PARI_END ", h);\
);
